[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "ffsim"
requires-python = ">=3.9"
version = "0.0.60.dev"
description = "Faster simulations of fermionic quantum circuits."
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "jax",
    "numpy",
    "opt_einsum",
    "orjson",
    "pyscf >= 2.9",
    "qiskit >= 1.3",
    "scipy",
    "typing-extensions",
]

[project.urls]
Homepage = "https://github.com/qiskit-community/ffsim"
Documentation = "https://qiskit-community.github.io/ffsim/"

[project.optional-dependencies]
dev = [
    "coverage",
    "maturin",
    "mypy",
    "myst-parser",
    "nbmake",
    "nbsphinx",
    "pre-commit",
    "pytest",
    "qiskit[visualization]",
    "qiskit-sphinx-theme",
    "ruff == 0.9.9",
    "sphinx",
    "sphinx-autodoc-typehints",
]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "ffsim._lib"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
files = ["python/**/*.py", "python/**/*.pyi", "tests/**/*.py", "docs/**/*.py"]

[tool.ruff]
src = ["python"]
include = [
    "pyproject.toml",
    "python/**/*.py",
    "python/**/*.pyi",
    "tests/**/*.py",
    "tests/**/*.pyi",
    "docs/**/*.py",
    "docs/**/*.pyi",
    "docs/**/*.ipynb",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "NPY", "NPY201"]

[tool.cibuildwheel]
build = "cp39-macosx* cp39-manylinux_x86_64 cp39-manylinux_aarch64"
test-requires = "pytest"
test-command = "pytest {project}/tests"

[tool.cibuildwheel.linux]
# Set the build image ONLY for aarch64.
# x86_64 will continue to use its default (manylinux2014).
manylinux-aarch64-image = "quay.io/pypa/manylinux_2_34_aarch64"

before-all = """
  set -ex
  if [ "$(uname -m)" = "aarch64" ]; then
    # new environment for aarch64 image
    dnf install -y openssl-devel rust cargo openblas-devel
  else
    # Original environment for x86_64 linux
    # mirrorlist.centos.org doesn't exist anymore
    # Workaround from https://serverfault.com/a/1161847
    sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo && sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo && yum install -y openssl-devel rust cargo openblas-devel
  fi
"""
